#!/usr/bin/env bash
# Clone floci-io/floci (AWS emulator) and prepare Docker orchestration for SCAS cloud labs.
#
# Usage:
#   ./scripts/floci/floci-setup.sh           # clone vendor + JVM build (works on Pi 4 / no-LSE ARM)
#   ./scripts/floci/floci-setup.sh --image   # published native image (needs ARM LSE — Pi 5+, not Pi 4)
#   ./scripts/floci/floci-setup.sh --auto    # --image if CPU supports native image, else JVM build
#   ./scripts/floci/floci-setup.sh --pull    # refresh vendor clone only

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
FLOCI_DIR="${REPO_ROOT}/infrastructure/floci"
VENDOR_DIR="${REPO_ROOT}/vendor/floci-aws"
FLOCI_REPO="${FLOCI_REPO_URL:-https://github.com/floci-io/floci.git}"
FLOCI_REF="${FLOCI_REF:-main}"
USE_IMAGE=0
AUTO_MODE=0
PULL_ONLY=0

# shellcheck source=floci-bridge.sh
source "${SCRIPT_DIR}/floci-bridge.sh"

for arg in "$@"; do
  case "$arg" in
    --image) USE_IMAGE=1 ;;
    --auto)  AUTO_MODE=1 ;;
    --pull)  PULL_ONLY=1 ;;
    -h|--help)
      echo "Usage: $0 [--auto|--image|--pull]"
      echo "  --auto   Prefer published image when CPU supports it; else JVM build (recommended for UI)"
      echo "  --image  Published floci/floci native image (fast; requires ARM LSE on aarch64)"
      echo "  --pull   git pull vendor/floci-aws only"
      echo "  (default) JVM source build — slower first run, works on Raspberry Pi 4 / Cortex-A72"
      exit 0
      ;;
  esac
done

if [ "$AUTO_MODE" = "1" ]; then
  if scas_floci_native_image_supported; then
    USE_IMAGE=1
    echo "ℹ️  CPU supports Floci native image — using --image"
  else
    USE_IMAGE=0
    echo "⚠️  This CPU lacks ARM LSE/atomics (common on Raspberry Pi 4 / Cortex-A72)."
    echo "   Published floci/floci:* native images will crash here."
    echo "   Falling back to JVM source build (first build is slow)."
  fi
elif [ "$USE_IMAGE" = "1" ] && ! scas_floci_native_image_supported; then
  echo "⚠️  --image requested but this CPU lacks ARM LSE/atomics."
  echo "   Native image will fail with: required CPU features … LSE"
  echo "   Switching to JVM source build. (Force native anyway: SCAS_FLOCI_FORCE_NATIVE=1)"
  if [ "${SCAS_FLOCI_FORCE_NATIVE:-0}" != "1" ]; then
    USE_IMAGE=0
  fi
fi

echo "========================================================="
echo "☁️  SCAS Floci setup (AWS emulator for scenarios 05–21)"
echo "========================================================="
echo ""

command -v docker >/dev/null 2>&1 || { echo "❌ Docker is required."; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "❌ Docker Compose v2 is required."; exit 1; }
echo "✅ Docker: $(docker --version | head -1)"
echo ""

mkdir -p "${FLOCI_DIR}/data" "${FLOCI_DIR}/init/ready.d"
scas_floci_prepare_data_dir "${FLOCI_DIR}/data"

if [ ! -f "${FLOCI_DIR}/.env" ]; then
  cp "${FLOCI_DIR}/.env.example" "${FLOCI_DIR}/.env"
  echo "✅ Created ${FLOCI_DIR}/.env"
else
  # Ensure memory storage (hybrid can 500 on some Linux/aarch64 hosts)
  if grep -q '^FLOCI_STORAGE_MODE=' "${FLOCI_DIR}/.env"; then
    sed -i.bak 's/^FLOCI_STORAGE_MODE=.*/FLOCI_STORAGE_MODE=memory/' "${FLOCI_DIR}/.env" 2>/dev/null \
      || sed -i '' 's/^FLOCI_STORAGE_MODE=.*/FLOCI_STORAGE_MODE=memory/' "${FLOCI_DIR}/.env"
    rm -f "${FLOCI_DIR}/.env.bak"
  else
    echo 'FLOCI_STORAGE_MODE=memory' >> "${FLOCI_DIR}/.env"
  fi
fi

if [ "$USE_IMAGE" = "1" ]; then
  sed -i.bak 's/^FLOCI_USE_IMAGE=.*/FLOCI_USE_IMAGE=1/' "${FLOCI_DIR}/.env" 2>/dev/null \
    || sed -i '' 's/^FLOCI_USE_IMAGE=.*/FLOCI_USE_IMAGE=1/' "${FLOCI_DIR}/.env"
  rm -f "${FLOCI_DIR}/.env.bak"
  echo "✅ Mode: published image (${FLOCI_IMAGE:-floci/floci:latest-compat})"
else
  sed -i.bak 's/^FLOCI_USE_IMAGE=.*/FLOCI_USE_IMAGE=0/' "${FLOCI_DIR}/.env" 2>/dev/null \
    || sed -i '' 's/^FLOCI_USE_IMAGE=.*/FLOCI_USE_IMAGE=0/' "${FLOCI_DIR}/.env"
  rm -f "${FLOCI_DIR}/.env.bak"

  if [ -d "${VENDOR_DIR}/.git" ]; then
    echo "📦 Updating vendor/floci-aws..."
    git -C "${VENDOR_DIR}" fetch origin
    git -C "${VENDOR_DIR}" checkout "${FLOCI_REF}" 2>/dev/null || git -C "${VENDOR_DIR}" pull --ff-only
  else
    echo "📥 Cloning ${FLOCI_REPO} → vendor/floci-aws ..."
    mkdir -p "${REPO_ROOT}/vendor"
    git clone --depth 1 --branch "${FLOCI_REF}" "${FLOCI_REPO}" "${VENDOR_DIR}"
  fi
  echo "✅ vendor/floci-aws ready ($(git -C "${VENDOR_DIR}" rev-parse --short HEAD))"
fi

if [ "$PULL_ONLY" = "1" ]; then
  echo "Done (--pull only)."
  exit 0
fi

# Persist Floci flags for scenario labs
FLOCI_ENV_FILE="${REPO_ROOT}/.floci.env"
cat > "${FLOCI_ENV_FILE}" << EOF
# Generated by scripts/floci/floci-setup.sh — source before cloud-track labs
export SCAS_FLOCI_ENABLED=1
export SCAS_FLOCI_ENDPOINT=http://127.0.0.1:4566
export SCAS_FLOCI_AWS_ACCESS_KEY_ID=test
export SCAS_FLOCI_AWS_SECRET_ACCESS_KEY=test
export AWS_ENDPOINT_URL=http://127.0.0.1:4566
export AWS_DEFAULT_REGION=us-east-1
# Do not set AWS_ACCESS_KEY_ID here — scenario labs export fake "leaked" CI keys for exfil JSON.
EOF
echo "✅ Wrote ${FLOCI_ENV_FILE}"

COMPOSE_FILE="${FLOCI_DIR}/docker-compose.yml"
if [ "$USE_IMAGE" = "1" ]; then
  COMPOSE_FILE="${FLOCI_DIR}/docker-compose.image.yml"
  echo ""
  echo "🐳 Pulling Floci image..."
  docker compose -f "${COMPOSE_FILE}" --env-file "${FLOCI_DIR}/.env" pull
else
  echo ""
  echo "🐳 Building Floci from source (first build may take several minutes)..."
  docker compose -f "${COMPOSE_FILE}" --env-file "${FLOCI_DIR}/.env" build
fi

echo ""
echo "========================================================="
echo "✅ Floci setup complete"
echo "========================================================="
echo ""
echo "Next:"
echo "  1. Start emulator:  ./scripts/floci/floci-up.sh"
echo "  2. Load env:        source .floci.env"
echo "  3. Run a cloud lab: cd scenarios/05-build-compromise && cat FLOCI.md"
echo ""
echo "Integrated scenarios: 05, 06, 14, 17, 21"
echo "Docs: documentation/guides/FLOCI_INTEGRATION.md"
echo ""
