#!/bin/bash

# SCAS-FP-RN-8d4f2c9a1e7b3065 — Supply Chain Attack Simulator © Raja Nagori
# Contributor helper: chmod, .testbench.env, dirs, a minimal .scas.env.
# It does not run npm install. Workshops should use ./install.sh from the repo root.
#
# Safe to run from any cwd: paths are resolved from the repo root (parent of this script).
#
# Usage:
#   ./scripts/setup/setup.sh        # interactive confirm
#   ./scripts/setup/setup.sh -y     # non-interactive (called from ./install.sh)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
cd "${REPO_ROOT}"
TESTBENCH_ENV_FILE="${REPO_ROOT}/.testbench.env"
YES=0

for arg in "$@"; do
    case "$arg" in
        -y|--yes) YES=1 ;;
        -h|--help)
            echo "Usage: ./scripts/setup/setup.sh [-y]"
            echo "Enables TESTBENCH_MODE, chmod's scenario setup.sh, writes a minimal .scas.env."
            echo "Front door for learners: ./install.sh"
            exit 0
            ;;
        *)
            echo "Unknown option: $arg"
            echo "Usage: ./scripts/setup/setup.sh [-y]"
            exit 1
            ;;
    esac
done

echo "========================================================="
echo "🔐 Supply Chain Attack Testbench - Setup"
echo "========================================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check OS
echo "📋 Checking system requirements..."
echo ""

OS="$(uname -s)"
case "${OS}" in
    Linux*)     MACHINE=Linux;;
    Darwin*)    MACHINE=Mac;;
    CYGWIN*)    MACHINE=Cygwin;;
    MINGW*)     MACHINE=MinGw;;
    *)          MACHINE="UNKNOWN:${OS}"
esac

echo -e "${BLUE}Operating System: ${MACHINE}${NC}"
echo ""

# Check prerequisites
echo "🔍 Checking prerequisites..."
echo ""

MISSING_DEPS=()

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}❌ Node.js not found${NC}"
    MISSING_DEPS+=("Node.js 16+")
else
    NODE_VERSION=$(node --version)
    echo -e "${GREEN}✅ Node.js: ${NODE_VERSION}${NC}"
fi

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}❌ npm not found${NC}"
    MISSING_DEPS+=("npm")
else
    NPM_VERSION=$(npm --version)
    echo -e "${GREEN}✅ npm: ${NPM_VERSION}${NC}"
fi

# Check Python 3
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}❌ Python 3 not found${NC}"
    MISSING_DEPS+=("Python 3.8+")
else
    PYTHON_VERSION=$(python3 --version | awk '{print $2}')
    echo -e "${GREEN}✅ Python3: ${PYTHON_VERSION}${NC}"
fi

echo ""

# Exit if missing required dependencies
if [ ${#MISSING_DEPS[@]} -gt 0 ]; then
    echo -e "${RED}Missing required dependencies:${NC}"
    for dep in "${MISSING_DEPS[@]}"; do
        echo "  - $dep"
    done
    echo ""
    echo "Please install the missing dependencies and run this script again."
    exit 1
fi

echo "========================================================="
echo "This script turns on TESTBENCH_MODE, chmod's lab setup.sh"
echo "files, and writes a minimal .scas.env."
echo "npm workspaces are installed by ./install.sh, not here."
echo ""
echo -e "${YELLOW}⚠️  This environment contains intentionally vulnerable code${NC}"
echo -e "${YELLOW}   for educational purposes only.${NC}"
echo "========================================================="
echo ""

if [ "$YES" != "1" ]; then
    read -p "Do you want to continue? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 1
    fi
fi

# Enable testbench mode
echo ""
echo "🔧 Configuring environment..."
export TESTBENCH_MODE=enabled
if [ ! -f "${TESTBENCH_ENV_FILE}" ] || ! grep -q '^export TESTBENCH_MODE=enabled$' "${TESTBENCH_ENV_FILE}"; then
    cat > "${TESTBENCH_ENV_FILE}" << 'EOF'
export TESTBENCH_MODE=enabled
EOF
fi
echo -e "${GREEN}✅ TESTBENCH_MODE enabled for current shell${NC}"
echo -e "${GREEN}✅ Persistent env file: ${TESTBENCH_ENV_FILE}${NC}"

SCAS_ENV_FILE="${REPO_ROOT}/.scas.env"
if [ ! -f "${SCAS_ENV_FILE}" ]; then
    cat > "${SCAS_ENV_FILE}" << 'EOF'
# SCAS session environment — generated by scripts/setup/setup.sh
# Usage:  source .scas.env
# ./install.sh overwrites this with ES / Floci exports when you run the workshop stack.

_SCAS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"

if [ -f "${_SCAS_ROOT}/.testbench.env" ]; then
  # shellcheck disable=SC1091
  source "${_SCAS_ROOT}/.testbench.env"
fi
export TESTBENCH_MODE="${TESTBENCH_MODE:-enabled}"
unset _SCAS_ROOT
EOF
    echo -e "${GREEN}✅ Wrote ${SCAS_ENV_FILE}${NC}"
else
    echo -e "${GREEN}✅ Kept existing ${SCAS_ENV_FILE}${NC}"
fi
echo ""
echo "Every session (repo root):"
echo "  source .scas.env"

# Make all setup scripts executable
echo ""
echo "🔐 Making setup scripts executable..."
find scenarios -name "setup.sh" -type f -exec chmod +x {} \;
echo -e "${GREEN}✅ Scripts configured${NC}"

# Create necessary directories
echo ""
echo "📁 Creating directory structure..."
mkdir -p logs
mkdir -p detection-tools
mkdir -p docs
echo -e "${GREEN}✅ Directories created${NC}"

# Setup complete
echo ""
echo "========================================================="
echo -e "${GREEN}✅ Setup Complete!${NC}"
echo "========================================================="
echo ""
echo "Next:"
echo ""
echo "1. source .scas.env"
echo ""
echo "2. First lab (typosquatting):"
echo "   cd scenarios/01-typosquatting"
echo "   ./setup.sh"
echo "   Walkthrough: documentation/scenario-guides/zero-to-hero/ZERO_TO_HERO_SCENARIO_01.md"
echo ""
echo "3. Prefer the installer next time (npm + optional ES/Floci):"
echo "   ./install.sh"
echo ""
echo "4. Clean up after a lab run:"
echo "   ./scripts/setup/teardown.sh"
echo ""
echo "Optional Floci cloud track (after Docker is up):"
echo "   ./scripts/floci/floci-setup.sh"
echo "   ./scripts/floci/floci-up.sh && source .floci.env"
echo ""
echo "Disable the gate in this shell only:"
echo "   unset TESTBENCH_MODE"
echo ""
echo "Reminders:"
echo "   - Education only, isolated machines"
echo "   - Never publish lab malware"
echo "   - Payloads need TESTBENCH_MODE=enabled"
echo ""
echo "Docs hub: documentation/getting-started/ZERO_TO_HERO.md"
echo ""

