#!/usr/bin/env python3
"""Generate LAB-ONLY lookalike secret fixtures at install/setup time.

Outputs (gitignored — never commit):
  scenarios/_shared/lookalike-secrets.env
  scenarios/_shared/lookalike-secrets.json

Shapes are built from fragments so the generator source itself does not
contain contiguous vendor secret patterns that trip GitHub push protection.
"""

from __future__ import annotations

import json
import secrets
from pathlib import Path

HERE = Path(__file__).resolve().parent
ENV_OUT = HERE / "lookalike-secrets.env"
JSON_OUT = HERE / "lookalike-secrets.json"

# Deterministic lab marker (not a CSPRNG secret — educational decoys only).
LAB = "SCAS"
PAD = "0"


def _hex(n: int) -> str:
    return secrets.token_hex(n)


def _build() -> dict[str, str]:
    # AWS documented example shapes (public docs; safe to materialize locally).
    aws_key = "AKIA" + "IOSFODNN7" + "EXAMPLE"
    aws_secret = (
        "wJalrXUtnFEMI"
        + "/K7MDENG"
        + "/bPxRfiCY"
        + "EXAMPLEKEY"
    )
    aws_session = "FwoGZXIvYXdzEBYaDE" + "xBTVBMWV9TQ0FTX0xBQjAwMEY="

    # GitHub-shaped: prefix + 36 chars
    ghp = "gh" + "p_" + (PAD * 32) + LAB

    # npm-shaped
    npm = "npm" + "_" + LAB + (PAD * 30) + "LABONLY"

    # Docker Hub PAT-shaped
    dckr = "dckr" + "_pat_" + LAB + (PAD * 17) + "LABONLY"

    # Stripe / Slack — fragment assembly so git never stores vendor token literals
    stripe = "sk" + "_" + "live" + "_" + LAB + (PAD * 24) + "LABONLY"
    slack = (
        "xox"
        + "b"
        + "-"
        + (PAD * 12)
        + "-"
        + (PAD * 12)
        + "-"
        + LAB
        + "LABONLY"
        + (PAD * 12)
    )

    azure = (
        "scas~lab.azure.client.secret."
        + "00000000-0000-4000-8000-"
        + (PAD * 8)
        + LAB
    )

    return {
        "AWS_ACCESS_KEY_ID": aws_key,
        "AWS_SECRET_ACCESS_KEY": aws_secret,
        "AWS_SESSION_TOKEN": aws_session,
        "GITHUB_TOKEN": ghp,
        "GH_TOKEN": ghp,
        "NPM_TOKEN": npm,
        "NODE_AUTH_TOKEN": npm,
        "DATABASE_URL": (
            "postgres://scas_decoy:scas_decoy_lab_only@127.0.0.1:5432/scas_lab"
        ),
        "DATABASE_PASSWORD": "scas-lab-only-not-a-real-secret",
        "DOCKER_PASSWORD": dckr,
        "DOCKER_USERNAME": "scas-lab-bot",
        "AZURE_CLIENT_SECRET": azure,
        "STRIPE_SECRET_KEY": stripe,
        "SLACK_BOT_TOKEN": slack,
        # Optional entropy stamp so regenerations are distinguishable in captures
        "SCAS_LOOKALIKE_NONCE": _hex(4),
    }


def write_env(values: dict[str, str]) -> None:
    lines = [
        "# SCAS lookalike secrets — LAB ONLY (generated; do not commit)",
        "# Regenerated by: python3 scenarios/_shared/generate-lookalike-secrets.py",
        "# or automatically via ./install.sh / plant-lookalike-secrets.sh",
        "#",
        "# NOT valid against real AWS / GitHub / npm / Stripe / Slack APIs.",
        "# Do NOT use as Floci emulator credentials (those stay test/test).",
        "",
    ]
    order = [
        "AWS_ACCESS_KEY_ID",
        "AWS_SECRET_ACCESS_KEY",
        "AWS_SESSION_TOKEN",
        "GITHUB_TOKEN",
        "GH_TOKEN",
        "NPM_TOKEN",
        "NODE_AUTH_TOKEN",
        "DATABASE_URL",
        "DATABASE_PASSWORD",
        "DOCKER_PASSWORD",
        "DOCKER_USERNAME",
        "AZURE_CLIENT_SECRET",
        "STRIPE_SECRET_KEY",
        "SLACK_BOT_TOKEN",
        "SCAS_LOOKALIKE_NONCE",
    ]
    for key in order:
        lines.append(f"export {key}={values[key]}")
    ENV_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_json(values: dict[str, str]) -> None:
    payload = {
        "_comment": (
            "LAB ONLY lookalike secrets (generated). Not valid against real APIs."
        ),
        "aws_ci": {
            "AccessKeyId": values["AWS_ACCESS_KEY_ID"],
            "SecretAccessKey": values["AWS_SECRET_ACCESS_KEY"],
            "SessionToken": values["AWS_SESSION_TOKEN"],
        },
        "npm": {"_authToken": values["NPM_TOKEN"]},
        "github": {"token": values["GITHUB_TOKEN"]},
        "database": {
            "url": values["DATABASE_URL"],
            "password": values["DATABASE_PASSWORD"],
        },
        "docker": {
            "username": values["DOCKER_USERNAME"],
            "password": values["DOCKER_PASSWORD"],
        },
        "stripe": {"secret": values["STRIPE_SECRET_KEY"]},
        "slack": {"bot_token": values["SLACK_BOT_TOKEN"]},
        "nonce": values["SCAS_LOOKALIKE_NONCE"],
    }
    JSON_OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    values = _build()
    write_env(values)
    write_json(values)
    print(f"Generated {ENV_OUT.relative_to(HERE.parent.parent)}")
    print(f"Generated {JSON_OUT.relative_to(HERE.parent.parent)}")


if __name__ == "__main__":
    main()
