import type { ScenarioLearn } from './types.js';

function walkthrough(id: string): string {
  return `documentation/scenario-guides/zero-to-hero/ZERO_TO_HERO_SCENARIO_${id}.md`;
}

function learn(
  partial: Omit<ScenarioLearn, 'walkthrough'> & { id: string },
): ScenarioLearn {
  const { id, ...rest } = partial;
  return { ...rest, walkthrough: walkthrough(id) };
}

/** Compact coaching for the dashboard Guide tab. Order follows SCENARIO_LEARNING_PATH. */
export const LEARN: Record<string, ScenarioLearn> = {
  '01': learn({
    id: '01',
    minutes: 15,
    track: 'foundation',
    why: 'A one-character typo of a real package name. This is the first capture on localhost, so you see the whole loop before the labs get weird.',
    youWill: {
      prepare: 'Run setup, then start the mock collector on :3000.',
      execute: 'Install request-lib (the typosquat) into victim-app and start it with TESTBENCH_MODE on.',
      observe: 'Hit /captured-data. You want at least one JSON capture, not an empty array.',
    },
    expect: 'captures[] with env/hostname-style fields posted to 127.0.0.1:3000.',
    next: '02',
    nextTitle: 'Dependency confusion',
  }),
  '02': learn({
    id: '02',
    minutes: 20,
    track: 'foundation',
    why: 'npm prefers a public package with the same name as an internal one. The attacker registry on :4874 wins if scopes are wrong.',
    youWill: {
      prepare: 'Setup, then start the mock on :3000 and the attacker registry on :4874.',
      execute: 'Install from corporate-app so the confuse-named package comes off the fake registry.',
      observe: 'Capture should show the public-name payload, not the internal package.',
    },
    expect: 'A capture from the confused package. Registry logs on :4874 help if the app stays quiet.',
    next: '03',
    nextTitle: 'Compromised package',
  }),
  '03': learn({
    id: '03',
    minutes: 20,
    track: 'foundation',
    why: 'Same package name, later version, malicious maintainer. You run clean first, then swap the compromised tarball.',
    youWill: {
      prepare: 'Setup and start the mock on :3000.',
      execute: 'Start with the legitimate package, then install ../compromised-package/secure-validator and run again.',
      observe: 'The second run should exfil. The first run should not.',
    },
    expect: 'Empty (or boring) capture on the clean run, then a real capture after the swap.',
    next: '04',
    nextTitle: 'Malicious update',
  }),
  '04': learn({
    id: '04',
    minutes: 25,
    track: 'intermediate',
    why: 'A patch bump that looks routine. The update path is the attack, not a brand-new name.',
    youWill: {
      prepare: 'Setup and start the mock on :3000.',
      execute: 'Install the malicious utils-helper update into victim-app and start it.',
      observe: 'Look for postinstall or runtime exfil tied to the new version.',
    },
    expect: 'Capture keyed off the updated helper, not the original 1.x behavior.',
    next: '07',
    nextTitle: 'Transitive dependency',
  }),
  '07': learn({
    id: '07',
    minutes: 30,
    track: 'intermediate',
    why: 'You never npm-install the bad package by name. data-processor sits under something the app actually depends on.',
    youWill: {
      prepare: 'Setup and start the mock on :3000.',
      execute: 'npm install in victim-app, run the swap step that drops compromised data-processor into node_modules, then start.',
      observe: 'Capture from the nested package. Empty usually means the swap did not land.',
    },
    expect: 'Exfil from data-processor after the node_modules swap, not from the top-level app package.',
    next: '08',
    nextTitle: 'Package lock manipulation',
  }),
  '08': learn({
    id: '08',
    minutes: 25,
    track: 'intermediate',
    why: 'A lockfile pin that points at a different integrity/hash than you think. npm install trusts the lock.',
    youWill: {
      prepare: 'Setup, start the mock. Watch port 3000: the victim Express app also wants it, so stop the mock before npm start if the README says so.',
      execute: 'Install from the manipulated lockfile, then run the victim.',
      observe: 'Capture from the pinned-bad tree.',
    },
    expect: 'Install resolves the attacker copy. Capture on :3000 unless EADDRINUSE ate the mock.',
    next: '10',
    nextTitle: 'Git submodule attack',
  }),
  '10': learn({
    id: '10',
    minutes: 30,
    track: 'intermediate',
    why: 'git clone --recurse-submodules pulls a repo you did not audit. npm postinstall inside that submodule fires on a normal install.',
    youWill: {
      prepare: 'Setup builds the local git repos. Start the mock on :3000.',
      execute: 'Install victim deps so the submodule postinstall runs. Do not invoke postinstall.sh by hand.',
      observe: 'Capture from the submodule hook.',
    },
    expect: 'A postinstall-shaped capture. Empty usually means the submodule never cloned or the hook never ran.',
    next: '12',
    nextTitle: 'Workspace / monorepo',
  }),
  '12': learn({
    id: '12',
    minutes: 30,
    track: 'intermediate',
    why: 'A workspace package is trusted because it lives in the same repo. Poison packages/utils and the app still imports it.',
    youWill: {
      prepare: 'Setup, start the mock on :3000.',
      execute: 'Install workspace root, then api, then utils, then start victim-app.',
      observe: 'Capture from the workspace package, not a public registry name.',
    },
    expect: 'Exfil when victim-app loads @devcorp/utils (or the lab equivalent). MODULE_NOT_FOUND means an install step was skipped.',
    next: '13',
    nextTitle: 'Metadata manipulation',
  }),
  '13': learn({
    id: '13',
    minutes: 25,
    track: 'intermediate',
    why: 'package.json lies: homepage, repo URL, maintainers. The tarball is not what the metadata promised.',
    youWill: {
      prepare: 'Setup and start the mock on :3001 (this lab is not on 3000).',
      execute: 'Install the tampered clean-utils package and run the victim.',
      observe: 'GET /capture on :3001, not /captured-data on :3000.',
    },
    expect: 'Metadata-flavored exfil on :3001/capture.',
    next: '16',
    nextTitle: 'Package cache poisoning',
  }),
  '16': learn({
    id: '16',
    minutes: 25,
    track: 'intermediate',
    why: 'First install poisons the local cache. Second install looks offline-clean and still gets the bad bits.',
    youWill: {
      prepare: 'Setup, start the mock on :3016.',
      execute: 'npm install once (poisons cache), npm install again, then start the victim.',
      observe: 'Capture on :3016 after the second install path.',
    },
    expect: 'The second install still pulls the poisoned copy. Capture proves it.',
    next: '05',
    nextTitle: 'Build system compromise',
  }),
  '05': learn({
    id: '05',
    minutes: 40,
    track: 'advanced',
    why: 'The package on disk looks fine. The build spit out a tainted dist/. CI trusted the artifact.',
    youWill: {
      prepare: 'Setup, start the mock on :3000. Optional Floci seed if you are on the cloud track.',
      execute: 'Install from compromised-build/dist/ and run the victim.',
      observe: 'Capture plus optional Floci verify.',
    },
    expect: 'Exfil from the built artifact, not from the source tree you glanced at.',
    next: '06',
    nextTitle: 'Shai-Hulud (self-replicating)',
  }),
  '06': learn({
    id: '06',
    minutes: 60,
    track: 'advanced',
    why: 'Worm-style lab: harvest credentials, hit a mock CDN, pretend GitHub Actions, replicate. Four ports. Do 01-05 first.',
    youWill: {
      prepare: 'Setup, start CDN :3000, harvester :3001, GHA sim :3002, replication :3003.',
      execute: 'Install compromised data-processor and run victim-app.',
      observe: 'Harvested credentials on :3001/captured-credentials, not the usual /captured-data.',
    },
    expect: 'JSON with lookalike tokens (npmrc / AWS-style fixtures). Empty harvester means a sidecar died.',
    next: '09',
    nextTitle: 'Package signing bypass',
  }),
  '09': learn({
    id: '09',
    minutes: 35,
    track: 'advanced',
    why: 'A signature check that is theater. Unsigned or wrong-key packages still install.',
    youWill: {
      prepare: 'Setup and start the mock on :3000.',
      execute: 'Install unsigned secure-utils from the compromised-package folder and run.',
      observe: 'Capture proving the bypassed package actually ran.',
    },
    expect: 'Exfil from secure-utils. Empty capture means the install never loaded that module.',
    next: '11',
    nextTitle: 'Registry mirror poisoning',
  }),
  '11': learn({
    id: '11',
    minutes: 40,
    track: 'advanced',
    why: 'Your "internal" mirror on :4873 serves a poisoned copy while npm thinks it is on-policy.',
    youWill: {
      prepare: 'Setup, start mock :3000 and poisoned registry :4873. Folders appear only after ./setup.sh.',
      execute: 'Install from corporate-app against the mirror, then start.',
      observe: 'Capture from the mirrored package.',
    },
    expect: 'The mirror served the bad tarball. Registry exit(1) during compose wait is a known fail mode to fix, not a lab success.',
    next: '14',
    nextTitle: 'Container image supply chain',
  }),
  '14': learn({
    id: '14',
    minutes: 40,
    track: 'advanced',
    why: 'A container start path, not npm install. malicious-start.js is the victim step and it can sit there.',
    youWill: {
      prepare: 'Setup and start the mock on :3002.',
      execute: 'Run node malicious-start.js from victim-app. Give it a minute; do not assume npm start.',
      observe: 'GET /capture on :3002.',
    },
    expect: 'Container-flavored exfil on :3002. A hang on malicious-start.js is a lab bug, not you.',
    next: '15',
    nextTitle: 'Developer tool compromise',
  }),
  '15': learn({
    id: '15',
    minutes: 35,
    track: 'advanced',
    why: 'IDE/CLI helper that runs in the developer workspace, not a product dependency.',
    youWill: {
      prepare: 'Setup, start the mock on :3015.',
      execute: 'npm start on the victim so the malicious dev tool hooks in.',
      observe: 'Capture on :3015.',
    },
    expect: 'Exfil from the tool hook. MODULE_NOT_FOUND means setup did not plant the helper.',
    next: '17',
    nextTitle: 'Multi-stage attack chain',
  }),
  '17': learn({
    id: '17',
    minutes: 45,
    track: 'advanced',
    why: 'Stage 1 looks like a helper. Stage 2 is the real payload. You correlate both.',
    youWill: {
      prepare: 'Setup, start the mock on :3017. Optional Floci seed.',
      execute: 'Install stage1-access-lib and stage2-compromised-lib, then start.',
      observe: 'Capture that mentions stage1/stage2, not a single package name.',
    },
    expect: 'Two-stage evidence on :3017. Grep for stage1 if the JSON is noisy.',
    next: '18',
    nextTitle: 'Package manager plugin',
  }),
  '18': learn({
    id: '18',
    minutes: 30,
    track: 'advanced',
    why: 'An npm plugin hook runs during install/lifecycle. You did not add it to package.json dependencies on purpose.',
    youWill: {
      prepare: 'Setup, start the mock on :3018.',
      execute: 'Start the victim so plugin hooks fire.',
      observe: 'Capture from the plugin, not from app.js.',
    },
    expect: 'Hook-time exfil on :3018.',
    next: '19',
    nextTitle: 'SBOM manipulation',
  }),
  '19': learn({
    id: '19',
    minutes: 35,
    track: 'advanced',
    why: 'The SBOM says the tree is clean. The installed tree is not. Policy that only reads the SBOM file loses.',
    youWill: {
      prepare: 'Setup, start the mock on :3019. Optional Floci seed.',
      execute: 'Install deps and run the victim.',
      observe: 'Capture plus a mismatched SBOM vs node_modules story in the README.',
    },
    expect: 'Exfil on :3019 while the SBOM still looks boring.',
    next: '20',
    nextTitle: 'Package version confusion',
  }),
  '20': learn({
    id: '20',
    minutes: 25,
    track: 'advanced',
    why: 'The resolver picks the highest version tag, including a lookalike that should never have won.',
    youWill: {
      prepare: 'Setup, start the mock on :3020.',
      execute: 'npm install, then start. Highest version wins.',
      observe: 'Capture from the confused version, not the one in the comment you trusted.',
    },
    expect: 'The higher attacker version ran. Capture on :3020.',
    next: '21',
    nextTitle: 'Axios-style npm release',
  }),
  '21': learn({
    id: '21',
    minutes: 40,
    track: 'advanced',
    why: 'A lookalike of a popular HTTP client, installed from a local tarball. Beacon API, not /captured-data.',
    youWill: {
      prepare: 'Setup, start the mock on :3021.',
      execute: 'Install axios-like from the 1.14.1 tarball and run the victim.',
      observe: 'Hit /beacon. Do not curl /captured-data on this lab; that path is the wrong check.',
    },
    expect: 'beacons[] (or equivalent) on :3021/beacon after the compromised tarball loads.',
    next: '22',
    nextTitle: 'LiteLLM-style PyPI',
  }),
  '22': learn({
    id: '22',
    minutes: 40,
    track: 'advanced',
    why: 'Python/PyPI cousin of 21. venv + pip, mock_server.py on :3022. A clean litellm_like wheel is the miss.',
    youWill: {
      prepare: 'Setup (creates venv). Start the Python mock on :3022.',
      execute: 'pip install the compromised litellm-like package inside the venv, then python app.py.',
      observe: 'Capture JSON from the Python mock. {} means you imported the clean extra.',
    },
    expect: 'A non-empty capture after the malicious package import, not litellm_like 1.82.6 clean.',
    next: '23',
    nextTitle: 'Trivy supply chain attack',
  }),
  '23': learn({
    id: '23',
    minutes: 45,
    track: 'advanced',
    why: 'The scanner in CI is the payload. victim-ci talks to mock-c2 on :3023. Finish 01-05 before this one if you can.',
    youWill: {
      prepare: 'Setup, start mock-c2 on :3023. Optional Floci seed.',
      execute: 'npm install in victim-ci, then npm start.',
      observe: 'C2-style capture on :3023.',
    },
    expect: 'Beacon/exfil on the mock C2. This is a scanner-trust lab, not a package-typo lab.',
    next: '24',
    nextTitle: 'Slopsquatting',
  }),
  '24': learn({
    id: '24',
    minutes: 20,
    track: 'intermediate',
    why: 'An LLM invented python-asyncio-utils. That is not a typo of lodash. Catalog 404 is the check, not Levenshtein. Capture on :3024.',
    youWill: {
      prepare: 'Setup, start the mock on :3024.',
      execute: 'Run check-catalog.js on the hallucinated names, then npm start in victim-app.',
      observe: '404 for python-asyncio-utils, 200 for lodash, then a capture after start.',
    },
    expect: 'captures[] from python-asyncio-utils on 127.0.0.1:3024. Distinct from 01 (human typo).',
    next: '25',
    nextTitle: 'Compromised reusable GitHub Action',
  }),
  '25': learn({
    id: '25',
    minutes: 25,
    track: 'advanced',
    why: 'uses: action@v1, not a weird build script (05) and not Trivy (23). Diff the two YAML files.',
    youWill: {
      prepare: 'Setup, start the mock on :3025.',
      execute: 'Run gha-runner.js on workflows/unsafe.yml. Then read workflows/safe.yml.',
      observe: 'Capture on :3025. Auditor flags pull_request_target, contents: write, floating tag.',
    },
    expect: 'A capture from changed-files-like. Safe YAML should not share those IOCs.',
    next: '26',
    nextTitle: 'Malicious MCP server',
  }),
  '26': learn({
    id: '26',
    minutes: 20,
    track: 'advanced',
    why: 'The agent called read_env. 15 is an IDE plugin. Keys come from dummy.env, collector :3026.',
    youWill: {
      prepare: 'Setup, start mock :3026 and mcp-server :3926.',
      execute: 'Run victim-agent/agent.js with TESTBENCH_MODE on.',
      observe: 'Capture includes the lab dummy keys, not a production secret.',
    },
    expect: 'POST /collect from tools/call. Safe mode prints [SAFE MODE] and does not post.',
    next: '27',
    nextTitle: 'npm provenance bypass',
  }),
  '27': learn({
    id: '27',
    minutes: 25,
    track: 'advanced',
    why: 'Stop on the attestation. 09 is signing. 21 is Axios postinstall. 1.0.0 is OIDC-shaped, 1.0.1 is laptop publish.',
    youWill: {
      prepare: 'Setup, start the mock on :3027.',
      execute: 'check-provenance.js for 1.0.0 then 1.0.1, then npm start the dirty victim.',
      observe: '1.0.0 passes. 1.0.1 fails. Dirty load still captures.',
    },
    expect: 'Issuer mismatch on 1.0.1, then a capture on :3027 after the file: install.',
    next: '28',
    nextTitle: 'Go module confusion',
  }),
  '28': learn({
    id: '28',
    minutes: 30,
    track: 'advanced',
    why: 'Go GOPROXY on :3028, GOSUMDB=off as the self-own, replace that looks like a pin. Need Go on PATH for go run.',
    youWill: {
      prepare: 'Setup (packs the zip). Start the mock GOPROXY on :3028.',
      execute: 'GOPROXY=http://127.0.0.1:3028,off GOSUMDB=off go run -mod=mod . in victim-module. Or goproxy-client.js without Go.',
      observe: 'Capture from init() or the Node client. Read go.mod.replace-trap.',
    },
    expect: 'A collect on :3028. Distinct from npm 02 confusion.',
    next: '29',
    nextTitle: 'HF-style model artifact',
  }),
  '29': learn({
    id: '29',
    minutes: 20,
    track: 'advanced',
    why: 'ML-artifact track. 01-23 stay software. Fake hub on :3029, JSON weights, trust_remote_code runs modeling.py.',
    youWill: {
      prepare: 'Setup, start python3 infrastructure/mock_hub.py.',
      execute: 'load_model.py once clean, once with --trust-remote-code.',
      observe: 'Clean run refuses remote code. Unsafe run captures on :3029.',
    },
    expect: 'No torch. Capture only on the unsafe path with TESTBENCH_MODE on.',
    next: null,
  }),
};

export const LEARN_TRACK_ORDER: Record<ScenarioLearn['track'], string[]> = {
  foundation: ['01', '02', '03'],
  intermediate: ['04', '07', '08', '10', '12', '13', '16', '24'],
  advanced: ['05', '06', '09', '11', '14', '15', '17', '18', '19', '20', '21', '22', '23', '25', '26', '27', '28', '29'],
};
